import type { MessageKey } from './index'

export const ar = {
	'common.not_answered': 'لم تتم الإجابة',
	'common.choose_an_option': 'اختر خياراً',
	'common.choose_month': 'اختر شهراً',
	'common.choose_one_answer': 'اختر إجابة واحدة',
	'common.choose_all_that_apply': 'اختر كل ما ينطبق',
	'common.continue': 'متابعة',
	'common.back': 'رجوع',
	'common.problem': 'هناك مشكلة',
	'chrome.app_title': 'Primer Paso',
	'chrome.meta_description':
		'Primer Paso هو استبيان أولي لعملية التسوية الاستثنائية في إسبانيا لعام 2026، وهو مستضاف على primerpaso.org.',
	'chrome.brand': 'Primer Paso',
	'chrome.language_switcher_label': 'تبديل اللغة',
	'pages.start.eyebrow': 'المرحلة 1',
	'pages.start.title': 'تحقّق من نوع الدعم الذي قد تحتاجه لعملية التسوية',
	'pages.start.lead': 'استخدم هذا الاستبيان لفهم ما قد تكون عليه خطوتك التالية.',
	'pages.start.not_official': 'هذا ليس الطلب الحكومي الرسمي.',
	'pages.start.window_open': 'فترة التقديم الرسمية مفتوحة حتى 30 يونيو 2026.',
	'pages.start.resume': 'يمكنك التوقف والعودة لاحقاً.',
	'pages.start.what_to_expect_title': 'ما الذي يمكن توقّعه',
	'pages.start.expectation.duration': 'حوالي 5 إلى 8 دقائق',
	'pages.start.expectation.one_question': 'سؤال واحد في كل مرة',
	'pages.start.expectation.review': 'خطوة مراجعة قبل النتيجة',
	'pages.start.expectation.timeline': 'فكرة تقريبية عن موعد بدء إقامتك في إسبانيا',
	'pages.start.start_now': 'ابدأ الاستبيان',
	'pages.check_answers.eyebrow': 'مراجعة',
	'pages.check_answers.title': 'راجع إجاباتك',
	'pages.check_answers.hint': 'راجع هذه الإجابات قبل المتابعة. يمكنك تغيير أي إجابة.',
	'pages.check_answers.change': 'تغيير',
	'pages.check_answers.see_result': 'عرض النتيجة',
	'pages.check_answers.back': 'رجوع',
	'pages.handover.eyebrow': 'التسليم',
	'pages.handover.summary_title': 'الملخص',
	'pages.handover.title': 'ملخص للحفظ أو الطباعة أو المشاركة',
	'pages.handover.body':
		'استخدم هذا الملخص للاحتفاظ بنسخة من إجاباتك أو لمشاركته مع عامل دعم موثوق أو منظمة متعاونة.',
	'pages.handover.reference': 'رقم المرجع: {sessionId}',
	'pages.handover.generated_at': 'تاريخ الإنشاء: {generatedAt}',
	'pages.handover.next_step_title': 'الخطوة التالية الموصى بها',
	'pages.handover.checklist_title': 'ما الذي ينبغي تجهيزه',
	'pages.handover.answers_title': 'إجاباتك',
	'pages.handover.flags_title': 'نقاط قد تحتاج إلى انتباه',
	'pages.handover.action.print': 'طباعة هذا الملخص',
	'pages.handover.action.back_to_result': 'العودة إلى النتيجة',
	'pages.result.eyebrow': 'النتيجة',
	'pages.result.eligibility_title': 'الأهلية المحتملة',
	'pages.result.eligibility.likely_in_scope':
		'استناداً إلى إجاباتك، قد يكون هذا المسار مناسباً لوضعك.',
	'pages.result.eligibility.possible_but_needs_more_evidence':
		'استناداً إلى إجاباتك، قد يناسبك هذا المسار، لكنك قد تحتاج إلى مزيد من المستندات قبل التقديم.',
	'pages.result.eligibility.needs_specialist_review':
		'استناداً إلى إجاباتك، قد يظل هذا المسار مناسباً، لكن سيكون من الأسلم مراجعته مع الدعم قبل التقديم.',
	'pages.result.eligibility.not_enough_information_yet':
		'ليس واضحاً بعد ما إذا كان هذا المسار مناسباً، لأن بعض المعلومات المهمة لا تزال مفقودة أو غير مؤكدة.',
	'pages.result.eligibility.another_route_may_fit_better':
		'استناداً إلى إجاباتك، قد يكون مسار هجرة آخر أنسب.',
	'pages.result.next_step_title': 'خطوتك التالية',
	'pages.result.next_step.official_portal':
		'اذهب إلى بوابة التسوية الرسمية عندما تكون مستعداً للمتابعة.',
	'pages.result.next_step.collaborating_organisation':
		'خذ هذا الملخص إلى منظمة متعاونة قبل المتابعة.',
	'pages.result.next_step.collaborating_organisation_hint':
		'افتح القائمة الرسمية واختر منظمة متعاونة يمكنها مراجعة حالتك معك.',
	'pages.result.why_title': 'لماذا نعتقد ذلك',
	'pages.result.checklist_title': 'ما الذي ينبغي تجهيزه',
	'pages.result.checklist.already_have': 'ما لديك بالفعل',
	'pages.result.checklist.still_need': 'ما قد لا يزال ينقصك',
	'pages.result.checklist.discuss_with_support': 'ما الذي ينبغي السؤال عنه عند الحصول على الدعم',
	'pages.result.checklist.unresolved': 'ما الذي ينبغي التحقق منه أو شرحه',
	'pages.result.route.official_portal_body':
		'استخدم البوابة الحكومية الرسمية لعملية التسوية. إذا احتجت إلى مساعدة أولاً، يمكنك أيضاً أخذ هذا الملخص إلى منظمة متعاونة.',
	'pages.result.route.collaborating_organisation_body':
		'ابدأ بالقائمة الرسمية للمنظمات المتعاونة. خذ هذا الملخص معك حتى لا يضطروا للبدء من الصفر.',
	'pages.result.handover_title': 'احفظ أو اطبع أو شارك الملخص',
	'pages.result.handover.body':
		'احتفظ بنسخة من إجاباتك. ويمكنك أيضاً أخذ هذا الملخص إلى عامل دعم موثوق أو منظمة متعاونة.',
	'pages.result.how_to_apply_title': 'قبل التقديم',
	'pages.result.how_to_apply.body':
		'استخدم قناة التقديم الحكومية الرسمية ولا تنتظر حتى اللحظة الأخيرة.',
	'pages.result.how_to_apply.hint': 'فترة التقديم الرسمية مفتوحة حتى 30 يونيو 2026.',
	'pages.result.support_title': 'الحصول على دعم',
	'pages.result.support.body':
		'هذا الاستبيان ليس استشارة قانونية. وقد يعتمد الدعم المتاح بالقرب منك على المقاطعة التي أنت فيها: {province}.',
	'pages.result.flags_title': 'الإشارات التي ظهرت',
	'pages.result.reference_title': 'احتفِظ بهذا المرجع',
	'pages.result.reference_body': 'رقم المرجع: {sessionId}',
	'pages.result.action.official_portal': 'استخدام بوابة التسوية الرسمية',
	'pages.result.action.open_official_portal': 'فتح بوابة التسوية الرسمية',
	'pages.result.action.open_collaborators_pdf': 'فتح القائمة الرسمية للمنظمات المتعاونة',
	'pages.result.action.collaborators_pdf': 'عرض القائمة الرسمية للمنظمات المتعاونة',
	'pages.result.action.print_handover': 'طباعة أو حفظ ملخص التسليم',
	'pages.result.action.download_handover_json': 'تنزيل ملف JSON للتسليم',
	'pages.result.action.back_to_answers': 'العودة إلى الإجابات',
	'pages.result.action.start_again': 'ابدأ من جديد',
	'pages.confirmation.eyebrow': 'تأكيد',
	'pages.confirmation.title': 'نتيجتك جاهزة',
	'pages.confirmation.body': 'احتفِظ بهذه الصفحة. فهي تتضمن رقم المرجع ونسخة من إجاباتك.',
	'pages.confirmation.reference_number': 'رقم المرجع',
	'pages.confirmation.updated': 'تم التحديث',
	'pages.confirmation.hint': 'احفظ هذه الصفحة أو اطبعها أو التقط لها لقطة شاشة.',
	'pages.confirmation.action.view_answers': 'عرض إجاباتك',
	'pages.confirmation.action.back_to_result': 'العودة إلى النتيجة',
	'pages.confirmation.action.start_again': 'ابدأ من جديد',
	'eyebrows.session_setup': 'للبدء',
	'eyebrows.eligibility': 'الأهلية',
	'eyebrows.route_split': 'وضعك',
	'eyebrows.route_asylum': 'مستنداتك',
	'eyebrows.route_non_asylum': 'وضعك',
	'eyebrows.identity': 'مستنداتك',
	'eyebrows.evidence_cutoff': 'إثبات الإقامة',
	'eyebrows.evidence_recent': 'إثبات الإقامة',
	'eyebrows.specialist': 'احتياجات دعم إضافية',
	'eyebrows.routing': 'الدعم المحلي',
	'eyebrows.referral': 'الدعم المحلي',
	'eyebrows.support': 'احتياجات دعم إضافية',
	'eyebrows.contact': 'كيف يمكننا التواصل معك',
	'months.january': 'يناير',
	'months.february': 'فبراير',
	'months.march': 'مارس',
	'months.april': 'أبريل',
	'months.may': 'مايو',
	'months.june': 'يونيو',
	'months.july': 'يوليو',
	'months.august': 'أغسطس',
	'months.september': 'سبتمبر',
	'months.october': 'أكتوبر',
	'months.november': 'نوفمبر',
	'months.december': 'ديسمبر',
	'steps.language.title': 'اختر لغة',
	'steps.language.hint': 'يمكنك تغيير اللغة في أي وقت من دون فقدان إجاباتك.',
	'steps.language.check_answers_label': 'اللغة',
	'steps.language.error': 'اختر لغة.',
	'steps.language.options.es': 'Español',
	'steps.language.options.en': 'English',
	'steps.language.options.ar': 'العربية',
	'steps.language.options.fr': 'Français',
	'steps.completion_mode.title': 'لمن تملأ هذا الاستبيان؟',
	'steps.completion_mode.hint': 'اختر الخيار الذي يطابق هذه الجلسة بأفضل شكل.',
	'steps.completion_mode.check_answers_label': 'الشخص الذي تملأ له هذا الاستبيان',
	'steps.completion_mode.error': 'اختر لمن تملأ هذا الاستبيان.',
	'steps.completion_mode.options.self': 'لنفسي',
	'steps.completion_mode.options.someone_else': 'لشخص آخر، بإذنه',
	'steps.completion_mode.options.support_worker': 'أنا عامل دعم أو متطوع',
	'steps.in_spain_now.title': 'هل أنت في إسبانيا الآن؟',
	'steps.in_spain_now.check_answers_label': 'هل أنت في إسبانيا الآن؟',
	'steps.in_spain_now.error': 'اختر ما إذا كنت في إسبانيا الآن.',
	'steps.common.options.yes': 'نعم',
	'steps.common.options.no': 'لا',
	'steps.common.options.not_sure': 'لست متأكداً',
	'steps.residence_start.title': 'متى بدأت العيش في إسبانيا؟',
	'steps.residence_start.hint': 'يكفي شهر تقريبي.',
	'steps.residence_start.check_answers_label': 'متى بدأت العيش في إسبانيا',
	'steps.residence_start.error': 'اختر متى بدأت العيش في إسبانيا.',
	'steps.residence_start.month_error': 'اختر الشهر، أو اذكر أنك غير متأكد من الشهر.',
	'steps.residence_start.options.2024_or_earlier': 'في 2024 أو قبل ذلك',
	'steps.residence_start.options.2025': 'في 2025',
	'steps.residence_start.options.2026': 'في 2026',
	'steps.residence_start.options.not_sure': 'لست متأكداً',
	'steps.residence_start.month_prompt': 'أي شهر تقريباً؟',
	'steps.residence_start.month_unknown': 'لست متأكداً من الشهر',
	'steps.asylum_history.title': 'هل قدمت طلب لجوء أو حماية دولية في إسبانيا؟',
	'steps.asylum_history.check_answers_label': 'اللجوء أو الحماية الدولية في إسبانيا',
	'steps.asylum_history.error': 'اختر ما إذا كنت قد قدمت طلب لجوء أو حماية دولية في إسبانيا.',
	'steps.asylum_before_cutoff.title': 'هل كان ذلك الطلب قبل 1 يناير 2026؟',
	'steps.asylum_before_cutoff.check_answers_label': 'اللجوء أو الحماية الدولية قبل 1 يناير 2026',
	'steps.asylum_before_cutoff.error': 'اختر ما إذا كان ذلك الطلب قبل 1 يناير 2026.',
	'steps.five_month_stay.title': 'هل كنت تعيش في إسبانيا خلال الأشهر الخمسة الماضية؟',
	'steps.five_month_stay.body': 'هل كنت في إسبانيا خلال الأشهر الخمسة الماضية؟',
	'steps.five_month_stay.hint': 'الرحلات القصيرة إلى الخارج لا تكون دائماً مهمة.',
	'steps.five_month_stay.check_answers_label': 'هل كنت في إسبانيا خلال الأشهر الخمسة الماضية؟',
	'steps.five_month_stay.error': 'اختر ما إذا كنت في إسبانيا خلال الأشهر الخمسة الماضية.',
	'steps.five_month_stay.options.mostly_yes': 'في الغالب نعم، مع غيابات قصيرة',
	'steps.asylum_documents.title': 'هل لديك أي مستندات بشأن قضية اللجوء أو الحماية الخاصة بك؟',
	'steps.asylum_documents.hint': 'مثل إيصال تقديم أو مستند من الملف أو رسالة أو إشعار.',
	'steps.asylum_documents.check_answers_label': 'مستندات بشأن قضية اللجوء أو الحماية الخاصة بك',
	'steps.asylum_documents.error':
		'اختر ما إذا كانت لديك مستندات بشأن قضية اللجوء أو الحماية الخاصة بك.',
	'steps.non_asylum_route.title': 'أي من هذه الخيارات يبدو أقرب إلى وضعك؟',
	'steps.non_asylum_route.check_answers_label': 'ما الذي يبدو أقرب إلى وضعك',
	'steps.non_asylum_route.error': 'اختر خياراً واحداً على الأقل.',
	'steps.non_asylum_route.options.worked_in_spain': 'لقد عملت في إسبانيا',
	'steps.non_asylum_route.options.close_family_relevant':
		'لدي أفراد أسرة مقربون هنا قد تكون حالتهم ذات صلة بهذه العملية',
	'steps.non_asylum_route.options.vulnerable_situation': 'قد أحتاج إلى دعم بسبب وضع صعب أو هش',
	'steps.non_asylum_route.options.none': 'لا شيء من ذلك',
	'steps.identity_documents.title': 'ما وثائق الهوية التي لديك؟',
	'steps.identity_documents.check_answers_label': 'وثائق الهوية',
	'steps.identity_documents.error': 'اختر خياراً واحداً على الأقل.',
	'steps.identity_documents.options.current_passport': 'جواز سفر ساري',
	'steps.identity_documents.options.expired_passport': 'جواز سفر منتهي الصلاحية',
	'steps.identity_documents.options.national_identity_card': 'بطاقة هوية وطنية',
	'steps.identity_documents.options.asylum_document': 'وثيقة لجوء',
	'steps.identity_documents.options.travel_document': 'وثيقة سفر',
	'steps.identity_documents.options.no_identity_documents_now': 'ليست لدي الآن أي وثائق هوية معي',
	'steps.identity_documents.options.prefer_not_to_say': 'أفضل عدم الإجابة',
	'steps.evidence_before_cutoff.title':
		'هل لديك أي مستندات يمكن أن تساعد في إثبات أنك كنت تعيش بالفعل في إسبانيا قبل يناير 2026؟',
	'steps.evidence_before_cutoff.check_answers_label': 'مستندات قد تُظهر الإقامة قبل يناير 2026',
	'steps.evidence_before_cutoff.error': 'اختر خياراً واحداً على الأقل.',
	'steps.evidence_before_cutoff.options.padron_or_registration': 'تسجيل أو padrón',
	'steps.evidence_before_cutoff.options.housing_papers': 'مستندات سكن',
	'steps.evidence_before_cutoff.options.health_or_pharmacy': 'مستندات صحية أو صيدلية',
	'steps.evidence_before_cutoff.options.school_or_childcare': 'مستندات مدرسة أو رعاية أطفال',
	'steps.evidence_before_cutoff.options.work_papers': 'مستندات عمل',
	'steps.evidence_before_cutoff.options.organisation_or_church_letter':
		'رسائل من منظمة أو كنيسة أو عامل اجتماعي',
	'steps.evidence_before_cutoff.options.travel_or_transport': 'مستندات سفر أو نقل',
	'steps.evidence_before_cutoff.options.something_else_dated_named': 'شيء آخر يحمل تاريخاً واسمي',
	'steps.evidence_before_cutoff.options.none_yet': 'لا أملك أياً من هذه بعد',
	'steps.evidence_recent_months.title':
		'هل لديك أي مستندات من الأشهر الخمسة الماضية يمكن أن تساعد في إظهار أنك كنت تعيش هنا مؤخراً؟',
	'steps.evidence_recent_months.check_answers_label': 'مستندات من آخر 5 أشهر',
	'steps.evidence_recent_months.error': 'اختر خياراً واحداً على الأقل.',
	'steps.evidence_recent_months.options.housing_papers': 'مستندات سكن',
	'steps.evidence_recent_months.options.health_or_pharmacy': 'مستندات صحية أو صيدلية',
	'steps.evidence_recent_months.options.school_or_childcare': 'مستندات مدرسة أو رعاية أطفال',
	'steps.evidence_recent_months.options.work_papers': 'مستندات عمل',
	'steps.evidence_recent_months.options.organisation_or_church_letter':
		'رسائل من منظمة أو كنيسة أو عامل اجتماعي',
	'steps.evidence_recent_months.options.bank_or_money_transfer': 'سجلات مصرفية أو تحويلات مالية',
	'steps.evidence_recent_months.options.travel_or_dated_receipts': 'سفر أو إيصالات مؤرخة',
	'steps.evidence_recent_months.options.something_else_dated_named': 'شيء آخر يحمل تاريخاً واسمي',
	'steps.evidence_recent_months.options.none_yet': 'لا أملك أياً من هذه بعد',
	'steps.specialist_flags.title': 'هل هناك أي شيء قد يعني أنك تحتاج إلى مشورة متخصصة قبل التقديم؟',
	'steps.specialist_flags.check_answers_label': 'أمور قد تتطلب مشورة متخصصة',
	'steps.specialist_flags.error': 'اختر خياراً واحداً على الأقل.',
	'steps.specialist_flags.options.criminal_record_worry':
		'أشعر بالقلق من وجود سجل جنائي أو قضية جنائية',
	'steps.specialist_flags.options.identity_missing_or_mismatch':
		'وثائق هويتي مفقودة أو أن بياناتي لا تتطابق بين المستندات',
	'steps.specialist_flags.options.previous_refusal_needs_help':
		'تلقيت رفضاً في إجراء آخر وأحتاج إلى مساعدة لفهمه',
	'steps.specialist_flags.options.asylum_case_not_clear':
		'لست متأكداً مما حدث في قضية اللجوء الخاصة بي',
	'steps.specialist_flags.options.unsafe_sharing_digitally':
		'لا أشعر بالأمان عند مشاركة بعض المعلومات رقمياً',
	'steps.specialist_flags.options.urgent_human_support': 'أحتاج إلى دعم بشري عاجل',
	'steps.specialist_flags.options.want_specialist': 'أفضل التحدث مع مختص حول هذا الأمر',
	'steps.specialist_flags.options.none': 'لا شيء من ذلك',
	'steps.support_needs.title': 'ما نوع المساعدة الأكثر فائدة لك؟',
	'steps.support_needs.error': 'اختر خياراً واحداً على الأقل.',
	'steps.support_needs.check_answers_label': 'الدعم المطلوب',
	'steps.support_needs.options.another_language': 'مساعدة بلغة أخرى',
	'steps.support_needs.options.in_person_help': 'مساعدة حضورية',
	'steps.support_needs.options.phone_support': 'دعم عبر الهاتف',
	'steps.support_needs.options.help_using_phone_or_computer':
		'مساعدة في استخدام الهاتف أو الكمبيوتر',
	'steps.support_needs.options.help_scanning_or_printing':
		'مساعدة في مسح المستندات ضوئياً أو طباعتها',
	'steps.support_needs.options.help_gathering_papers': 'مساعدة لفهم المستندات التي ينبغي جمعها',
	'steps.support_needs.options.child_or_dependant_support':
		'مساعدة أيضاً للأطفال أو الأشخاص المعالين',
	'steps.support_needs.options.specialist_advice': 'مشورة متخصصة',
	'steps.province.title': 'في أي مقاطعة أنت؟',
	'steps.province.hint': 'يساعدنا هذا في عرض خيارات الدعم القريبة منك.',
	'steps.province.check_answers_label': 'المقاطعة',
	'steps.province.error': 'اختر مقاطعة.',
	'steps.province.options.madrid': 'مدريد',
	'steps.province.options.barcelona': 'برشلونة',
	'steps.province.options.valencia': 'فالنسيا',
	'steps.province.options.sevilla': 'إشبيلية',
	'steps.province.options.malaga': 'مالقة',
	'steps.province.options.alicante': 'أليكانتي',
	'steps.province.options.bizkaia': 'بيزكايا',
	'steps.province.options.zaragoza': 'سرقسطة',
	'steps.province.options.murcia': 'مرسية',
	'steps.province.options.other': 'مقاطعة أخرى',
	'steps.referral.title': 'هل تريد مساعدة في الخطوة التالية؟',
	'steps.referral.body':
		'بناءً على نتيجتك، قد ترغب في المساعدة على جمع المستندات أو التحدث مع مختص أو تقديم الطلب.',
	'steps.referral.error': 'اختر نوع المساعدة التي تريدها بعد ذلك.',
	'steps.referral.options.contact_me': 'نعم، أود أن يتواصل معي أحد',
	'steps.referral.options.show_options': 'نعم، اعرض لي خيارات الدعم القريبة مني',
	'steps.referral.options.no_thanks': 'لا، سأحتفظ بهذا الآن',
	'steps.contact.title': 'كيف ينبغي أن نتواصل معك؟',
	'steps.contact.hint': 'اختر الطريقة الأكثر أماناً.',
	'steps.contact.error': 'اختر كيف ينبغي أن نتواصل معك.',
	'steps.contact.detail_required_error': 'أدخل بيانات التواصل للطريقة التي اخترتها.',
	'steps.contact.detail_label': 'بيانات التواصل',
	'steps.contact.options.sms': 'رسالة نصية SMS',
	'steps.contact.options.whatsapp': 'واتساب',
	'steps.contact.options.phone': 'مكالمة هاتفية',
	'steps.contact.options.email': 'بريد إلكتروني',
	'steps.contact.options.do_not_contact_yet': 'لا تتواصلوا معي الآن',
	'steps.contact.options.through_organisation': 'من خلال المنظمة التي تساعدني الآن',
	'answers.residence_start.2024_or_earlier': '2024 أو قبل ذلك',
	'answers.residence_start.2026': '2026',
	'answers.residence_start.not_sure': 'لست متأكداً',
	'answers.residence_start.2025': '2025',
	'answers.residence_start.2025_month_unknown': '2025 — الشهر غير معروف',
	'answers.residence_start.2025_month': '{month} 2025',
	'answers.contact.with_value': '{method}: {value}',
	'result.reason.not_in_spain_now': 'ذكرت أنك لست في إسبانيا الآن.',
	'result.reason.after_cutoff': 'ذكرت أنك بدأت العيش في إسبانيا في 2026.',
	'result.reason.specialist_review':
		'تشير واحدة أو أكثر من إجاباتك إلى أن الحصول على دعم قبل التقديم سيكون أكثر أماناً.',
	'result.reason.specialist_review_criminal_record':
		'ذكرت أنك قد تقلق بشأن السجل الجنائي. من الأسلم مراجعة ذلك مع الدعم قبل التقديم.',
	'result.reason.specialist_review_identity':
		'ذكرت أن بعض تفاصيل الهوية قد تكون مفقودة أو غير متطابقة. من الأسلم مراجعة ذلك مع الدعم قبل التقديم.',
	'result.reason.not_enough_information':
		'لا تزال بعض التفاصيل المهمة عن وضعك أو عن التسلسل الزمني غير واضحة.',
	'result.reason.more_evidence':
		'قد تتوافق إجاباتك مع هذا المسار، لكنك قد تحتاج إلى مزيد من المستندات لدعم طلبك.',
	'result.reason.likely_in_scope':
		'تشير إجاباتك إلى أن التواريخ والمستندات التي لديك قد تتوافق مع هذا المسار.',
	'result.explanation.not_in_spain_now':
		'استناداً إلى إجاباتك، فغالباً ليس هذا هو المسار المناسب لك الآن.',
	'result.explanation.after_cutoff': 'استناداً إلى إجاباتك، فغالباً لا يكون هذا المسار الأنسب لوضعك.',
	'result.explanation.specialist_review':
		'تشير إجاباتك إلى أن مختصاً ينبغي أن يراجع وضعك قبل الخطوة التالية.',
	'result.explanation.not_enough_information': 'لا توجد معلومات كافية بعد لاقتراح أفضل خطوة تالية.',
	'result.explanation.more_evidence':
		'استناداً إلى إجاباتك، قد يكون هذا المسار مناسباً لوضعك، لكنك قد تحتاج إلى مزيد من المستندات قبل التقديم.',
	'result.explanation.likely_in_scope':
		'تشير إجاباتك إلى أنك قد تتمكن من استخدام عملية التسوية هذه.',
	'result.next_step.other_route_advice': 'اطلب المشورة بشأن ما إذا كان مسار هجرة آخر أنسب لوضعك.',
	'result.next_step.try_again_later': 'إذا تغيّر وضعك، يمكنك مراجعة هذا المسار مرة أخرى لاحقاً.',
	'result.next_step.keep_residence_documents': 'احتفِظ بأي مستندات تُظهر تاريخ إقامتك في إسبانيا.',
	'result.next_step.speak_to_specialist': 'تحدث مع منظمة دعم متخصصة قبل أن تقدّم الطلب.',
	'result.next_step.keep_papers_together': 'احتفِظ بوثائق هويتك وأي أدلة مؤرخة معاً من أجل المراجعة.',
	'result.next_step.confirm_timeline':
		'حاول التأكد تقريباً من موعد بدء إقامتك في إسبانيا وما إذا كنت قد عشت هنا خلال الأشهر الخمسة الماضية.',
	'result.next_step.ask_for_help_if_unsure':
		'إذا لم تكن متأكداً، فاستخدم الإكمال بمساعدة أو اطلب المساعدة من منظمة دعم.',
	'result.next_step.gather_before_cutoff':
		'حاول جمع مستندات مؤرخة تُظهر أنك كنت تعيش في إسبانيا قبل يناير 2026.',
	'result.next_step.gather_recent': 'واجمع أيضاً، إن أمكن، مستندات حديثة من آخر 5 أشهر.',
	'result.next_step.use_official_channel': 'استخدم قناة التقديم الرسمية قبل 30 يونيو 2026.',
	'result.flag.not_in_spain_now': 'لست في إسبانيا الآن',
	'result.flag.uncertain_timeline': 'المدة الزمنية غير مؤكدة',
	'result.flag.five_month_requirement_risk': 'احتمال وجود مشكلة في الاستمرارية',
	'result.flag.hard_gate_after_cutoff': 'بدء الإقامة كان بعد التاريخ الفاصل',
	'result.flag.criminal_record_concern': 'احتمال وجود قلق متعلق بسجل جنائي',
	'result.flag.identity_issue': 'مشكلة في الهوية',
	'result.flag.asylum_complexity': 'احتمال وجود تعقيد متعلق باللجوء',
	'result.flag.missing_identity_documents': 'وثائق الهوية مفقودة',
	'result.flag.continuity_concern': 'قلق بشأن الاستمرارية',
	'result.flag.family_support_needs': 'احتياجات دعم للأسرة أو المعالين',
	'result.checklist.item.identity_document_available': 'وثيقة هوية يمكنك إبرازها.',
	'result.checklist.item.asylum_case_documents_available':
		'مستندات تتعلق بقضية اللجوء أو الحماية الخاصة بك.',
	'result.checklist.item.before_cutoff_evidence_available':
		'أوراق قد تساعد في إظهار أنك كنت في إسبانيا قبل يناير 2026.',
	'result.checklist.item.recent_evidence_available': 'أوراق حديثة من آخر 5 أشهر.',
	'result.checklist.item.continuity_answer_positive':
		'إقامة حديثة في إسبانيا قد تتوافق مع هذا المسار.',
	'result.checklist.item.identity_document_needed': 'وثيقة هوية يمكنك استخدامها في الطلب.',
	'result.checklist.item.before_cutoff_evidence_needed':
		'أوراق مؤرخة تُظهر أنك كنت في إسبانيا قبل يناير 2026.',
	'result.checklist.item.recent_evidence_needed': 'أوراق حديثة من آخر 5 أشهر.',
	'result.checklist.item.asylum_case_documents_needed':
		'أي أوراق ما زالت لديك عن قضية لجوء أو حماية، إذا كان ذلك ينطبق على وضعك.',
	'result.checklist.item.official_document_requirements':
		'أحدث المتطلبات الرسمية للمستندات، بما في ذلك مستندات السجل الجنائي إذا كانت تنطبق على حالتك.',
	'result.checklist.item.practical_support_helpful':
		'مساعدة في اللغة أو الوصول الرقمي أو المسح الضوئي أو الطباعة أو فهم المستندات الأكثر أهمية.',
	'result.checklist.item.complex_case_review':
		'أي قلق يتعلق بالسجل الجنائي أو الهوية أو تاريخ اللجوء أو مشاركة المعلومات بأمان.',
	'result.checklist.item.another_route_advice': 'ما إذا كان مسار هجرة آخر قد يكون أنسب.',
	'result.checklist.item.confirm_timeline':
		'موعد بدء عيشك في إسبانيا، وما إذا كنت هنا خلال الأشهر الخمسة الماضية.',
	'result.checklist.item.continuity_concern': 'أي فجوات أو غياب خلال الأشهر الخمسة الماضية.',
	'result.checklist.item.identity_issue_to_explain': 'أي وثائق هوية مفقودة أو تفاصيل لا تتطابق.',
	'result.checklist.item.asylum_history_to_explain':
		'ما الذي حدث في أي إجراء لجوء أو حماية في إسبانيا.',
	'result.title.likely_in_scope': 'على الأرجح ضمن النطاق',
	'result.title.possible_but_needs_more_evidence':
		'قد يكون هذا المسار مناسباً، لكنك قد تحتاج إلى مزيد من المستندات أولاً',
	'result.title.needs_specialist_review': 'يحتاج إلى مراجعة متخصصة',
	'result.title.another_route_may_fit_better': 'غالباً ليس هذا هو المسار المناسب لك',
	'result.title.not_enough_information_yet':
		'نحتاج إلى مزيد قليل من المعلومات قبل اقتراح الخطوة التالية',
	'result.lead.likely_in_scope': 'قد تتمكن من استخدام هذا المسار',
	'result.lead.possible_but_needs_more_evidence':
		'قد يكون هذا المسار مناسباً، لكنك قد تحتاج إلى مزيد من المستندات أولاً',
	'result.lead.needs_specialist_review': 'قد تحتاج إلى مساعدة متخصصة قبل التقديم',
	'result.lead.not_enough_information_yet':
		'نحتاج إلى مزيد قليل من المعلومات قبل اقتراح الخطوة التالية',
	'result.lead.another_route_may_fit_better': 'غالباً ليس هذا هو المسار المناسب لك'
} satisfies Partial<Record<MessageKey, string>>
