import type { MessageKey } from './index'

export const ar = {
	'common.not_answered': 'لم تتم الإجابة',
	'common.choose_an_option': 'اختر خياراً',
	'common.continue': 'متابعة',
	'common.back': 'رجوع',
	'common.problem': 'هناك مشكلة',
	'common.change': 'تغيير',
	'common.see_result': 'عرض النتيجة',
	'common.review_answers': 'راجع إجاباتك',
	'common.start_again': 'ابدأ من جديد',
	'common.download_handover_pdf': 'تنزيل ملف PDF للملخص',
	'common.see_support_options': 'عرض خيارات الدعم',
	'common.open_official_portal': 'فتح البوابة الرسمية للتسوية',
	'common.back_to_answers': 'العودة إلى الإجابات',
	'common.visit_website': 'زيارة الموقع',
	'common.email': 'إرسال بريد إلكتروني',
	'common.call': 'اتصال',
	'common.open_directory': 'فتح الدليل',
	'chrome.skip_to_main': 'انتقل إلى المحتوى الرئيسي',
	'chrome.app_title': 'Primer Paso',
	'chrome.meta_description':
		'Primer Paso هو استبيان أولي لعملية التسوية الاستثنائية في إسبانيا لعام 2026، وهو مستضاف على primerpaso.org.',
	'chrome.brand': 'Primer Paso',
	'chrome.tagline': 'إرشاد مستقل بشأن عملية التسوية في إسبانيا لعام 2026',
	'chrome.primary_navigation': 'التنقل الرئيسي',
	'chrome.nav.home': 'الرئيسية',
	'chrome.nav.start': 'التحقق من الخطوة التالية',
	'chrome.nav.organisations': 'البحث عن منظمات',
	'chrome.footer.eyebrow': 'Primer Paso',
	'chrome.footer.title': 'حول هذه الأداة',
	'chrome.footer.body':
		'تساعد Primer Paso الأشخاص على فهم عملية التسوية الاستثنائية لعام 2026 في إسبانيا، وتحديد الوثائق أو المعلومات التي قد لا تزال ناقصة، واتخاذ قرار بشأن وقت استخدام البوابة الرسمية أو طلب الدعم.',
	'chrome.footer.attribution_prefix': 'طُوِّرت بواسطة',
	'chrome.footer.attribution_name': 'Radical Data',
	'chrome.footer.disclaimer': 'لا تحل محل الاستشارة القانونية ولا تشكل قراراً رسمياً.',
	'chrome.footer.link.official_portal': 'البوابة الرسمية',
	'chrome.language_switcher_label': 'اللغة',
	'pages.home.eyebrow': 'البدء',
	'pages.home.title': 'اختر كيف تريد أن تبدأ',
	'pages.home.meta_title': 'دعم لعملية التسوية الاستثنائية في إسبانيا 2026 | Primer Paso',
	'pages.home.meta_description':
		'يساعد Primer Paso الأشخاص على فهم عملية التسوية الاستثنائية في إسبانيا لعام 2026، ومعرفة الوثائق التي قد تكون ناقصة، واتخاذ قرار بين البوابة الرسمية أو طلب الدعم من منظمة متعاونة.',
	'pages.home.lead':
		'يمكنك استخدام الأداة لمعرفة الخطوة التالية أو الذهاب مباشرة إلى دليل الجهات المتعاونة.',
	'pages.home.choose': 'اختر خياراً',
	'pages.home.quiz_title': 'معرفة الخطوة التالية',
	'pages.home.quiz_body': 'أجب عن بعض الأسئلة للحصول على توجيه حذر حول المسار الذي قد يناسب حالتك.',
	'pages.home.quiz_action': 'ابدأ الأداة',
	'pages.home.directory_title': 'البحث عن جهة متعاونة',
	'pages.home.directory_body':
		'تصفح الدليل من دون إكمال النموذج. ابحث بالاسم أو المقاطعة أو بيانات الاتصال.',
	'pages.home.note_title': 'قبل أن تبدأ',
	'pages.home.note_body':
		'هذه الخدمة تقدم إرشاداً عملياً ولا تحل محل الاستشارة القانونية أو القرار الرسمي.',
	'pages.home.seo_intro_title': 'إرشاد واضح قبل البدء',
	'pages.home.seo_intro_body_1':
		'في Primer Paso يمكنك اختيار كيف تريد أن تبدأ: استبيان قصير أو الانتقال مباشرة إلى دليل المنظمات المتعاونة.',
	'pages.home.seo_intro_body_2':
		'هذه الأداة مخصّصة للأشخاص الذين يبحثون عن دعم في عملية التسوية الاستثنائية في إسبانيا لعام 2026. تساعدك على فهم المعلومات المهمة، والوثائق التي قد ما زلت تحتاج إليها، ومتى يكون من الأفضل طلب دعم بشري مباشر.',
	'pages.home.seo_intro_body_3':
		'هذه أداة إرشادية بحذر. لا تحل محل الاستشارة القانونية ولا تمثل قراراً رسمياً. هدفها مساعدتك على الاستعداد واختيار الخطوة التالية المناسبة بسرعة أكبر.',
	'pages.home.seo_help_title': 'ما الذي يمكنك فعله هنا',
	'pages.home.seo_help_item_1': 'الإجابة عن سؤال واحد في كل صفحة ثم مراجعة الإجابات قبل النتيجة.',
	'pages.home.seo_help_item_2': 'فهم ما إذا كانت البوابة الرسمية قد تناسب حالتك.',
	'pages.home.seo_help_item_3': 'العثور على منظمات متعاونة قد تقدم دعماً داخل إسبانيا.',
	'pages.home.seo_help_item_4': 'إعداد ملخص يمكن طباعته بالمعلومات الأساسية التي جمعتها.',
	'pages.home.seo_support_title': 'هل تبحث عن دعم عملي داخل إسبانيا؟',
	'pages.home.seo_support_body':
		'إذا كنت تعرف مسبقاً أنك تريد دعماً بشرياً، يمكنك الذهاب مباشرة إلى دليل المنظمات. وإذا كنت تفضل فهم وضعك أولاً، فابدأ بالاستبيان ثم قرر بين المسار الرسمي أو طلب المساعدة من منظمة متعاونة.',
	'pages.home.official_portal_action': 'البوابة الرسمية للتسوية',
	'pages.start.eyebrow': 'المرحلة 1',
	'pages.organisations.meta_title': 'البحث عن الجهات',
	'pages.organisations.meta_description':
		'تصفح الجهات المتعاونة حسب الاسم والمقاطعة وبيانات الاتصال.',
	'pages.organisations.eyebrow': 'الجهات المتعاونة',
	'pages.organisations.title': 'البحث عن جهة متعاونة',
	'pages.organisations.lead':
		'تصفح الدليل العام من دون إكمال الأداة. ابحث بالاسم أو الموقع أو بيانات الاتصال.',
	'pages.organisations.search_label': 'بحث',
	'pages.organisations.search_placeholder':
		'ابحث بالاسم أو المكان أو الهاتف أو البريد الإلكتروني أو الموقع',
	'pages.organisations.apply_filters': 'تطبيق الفلاتر',
	'pages.organisations.clear': 'مسح',
	'pages.organisations.summary.one': 'تم العثور على جهة واحدة',
	'pages.organisations.summary.many': 'تم العثور على {count} جهات',
	'pages.organisations.empty_title': 'لا توجد جهات تطابق هذه الفلاتر',
	'pages.organisations.empty_body': 'جرّب بحثاً أوسع أو تصفح الدليل كاملاً.',
	'pages.organisations.guidance_title': 'هل تحتاج إلى إرشاد شخصي أولاً؟',
	'pages.organisations.guidance_body':
		'إذا لم تكن متأكداً من أين تبدأ، فاستخدم الأداة أولاً ثم عد إلى الدليل.',
	'pages.organisations.action.view_details': 'عرض التفاصيل',
	'pages.organisations.action.browse_all': 'تصفح كل الجهات',
	'pages.organisations.action.start_screener': 'ابدأ الأداة',
	'pages.organisations.detail.meta_has_phone': 'الهاتف متاح',
	'pages.organisations.detail.meta_has_website': 'الموقع متاح',
	'pages.organisations.detail.lead': 'راجع قنوات التواصل وساعات العمل قبل التواصل مع هذه الجهة.',
	'pages.organisations.detail.contact_title': 'بيانات التواصل',
	'pages.organisations.detail.opening_hours_title': 'ساعات العمل',
	'pages.organisations.detail.guidance_body':
		'استخدم صفحة التفاصيل لاختيار طريقة التواصل الأكثر أماناً لوضعك.',
	'pages.start.title': 'تحقّق من نوع الدعم الذي قد تحتاجه لعملية التسوية',
	'pages.start.lead': 'استخدم هذا الاستبيان لفهم ما قد تكون عليه خطوتك التالية.',
	'pages.start.not_official': 'هذا ليس الطلب الحكومي الرسمي.',
	'pages.start.window_open': 'فترة التقديم الرسمية مفتوحة حتى 30 يونيو 2026.',
	'pages.start.resume': 'يمكنك التوقف والعودة لاحقاً.',
	'pages.start.what_to_expect_title': 'ما الذي يمكن توقّعه',
	'pages.start.expectation.duration': 'حوالي 5 إلى 8 دقائق',
	'pages.start.expectation.one_question': 'سؤال واحد في كل مرة',
	'pages.start.expectation.review': 'خطوة مراجعة قبل النتيجة',
	'pages.start.expectation.timeline':
		'ما إذا كنت في إسبانيا قبل 1 يناير 2026 وما إذا بقيت في إسبانيا طوال فترة الـ5 أشهر قبل تقديم الطلب',
	'pages.start.start_now': 'ابدأ الاستبيان',
	'pages.check_answers.eyebrow': 'مراجعة',
	'pages.check_answers.title': 'راجع إجاباتك',
	'pages.check_answers.hint': 'راجع هذه الإجابات قبل المتابعة. يمكنك تغيير أي إجابة.',
	'pages.handover.summary_title': 'الملخص',
	'pages.handover.title': 'ملخص للحفظ أو الطباعة أو المشاركة',
	'pages.handover.body':
		'استخدم هذا الملخص للاحتفاظ بنسخة من إجاباتك أو لمشاركته مع عامل دعم موثوق أو منظمة متعاونة.',
	'pages.handover.reference': 'رقم المرجع: {sessionId}',
	'pages.handover.generated_at': 'تاريخ الإنشاء: {generatedAt}',
	'pages.handover.generated_by': 'تم إنشاؤه بواسطة Primer Paso (primerpaso.org)',
	'pages.handover.links_title': 'روابط مفيدة',
	'pages.handover.link.official_portal': 'البوابة الرسمية لتسوية الوضع',
	'pages.handover.link.collaborators_pdf': 'القائمة الرسمية للجهات المتعاونة',
	'pages.handover.checklist_title': 'ما الذي ينبغي تجهيزه',
	'pages.handover.answers_title': 'إجاباتك',
	'pages.handover.flags_title': 'نقاط قد تحتاج إلى انتباه',
	'pages.result.eyebrow': 'النتيجة',
	'pages.result.eligibility_title': 'نتيجتك',
	'pages.result.next_step_title': 'خطوتك التالية',
	'pages.result.why_title': 'لماذا نعتقد ذلك',
	'pages.result.checklist_title': 'ما الذي ينبغي تجهيزه',
	'pages.result.checklist.already_have': 'ما لديك بالفعل',
	'pages.result.checklist.still_need': 'ما قد لا يزال ينقصك',
	'pages.result.checklist.discuss_with_support': 'أسئلة يُستحسن طرحها عند الحصول على الدعم',
	'pages.result.checklist.unresolved': 'ما الذي ينبغي التحقق منه أو شرحه',
	'pages.result.route.official_portal_body':
		'استخدم البوابة الحكومية الرسمية لعملية التسوية. إذا احتجت إلى مساعدة أولاً، يمكنك أيضاً أخذ هذا الملخص إلى منظمة متعاونة.',
	'pages.result.route.collaborating_organisation_body':
		'ابدأ بالقائمة الرسمية للمنظمات المتعاونة. خذ هذا الملخص معك حتى لا يضطروا للبدء من الصفر.',
	'pages.result.handover_title': 'احفظ أو اطبع أو شارك الملخص',
	'pages.result.handover.body':
		'احتفظ بنسخة من إجاباتك. ويمكنك أيضاً أخذ هذا الملخص إلى عامل دعم موثوق أو منظمة متعاونة.',
	'pages.result.how_to_apply_title': 'قبل التقديم',
	'pages.result.how_to_apply.body':
		'استخدم قناة التقديم الحكومية الرسمية ولا تنتظر حتى اللحظة الأخيرة.',
	'pages.result.how_to_apply.hint': 'فترة التقديم الرسمية مفتوحة حتى 30 يونيو 2026.',
	'pages.result.another_route.do_now_title': 'ما الذي ينبغي فعله الآن',
	'pages.result.another_route.do_now.body':
		'تحقّق من إجاباتك مرة أخرى، وخصوصاً التواريخ والتسلسل الزمني. وإذا كانت صحيحة، فاحفظ هذا الملخص وتوقف قبل متابعة هذا المسار.',
	'pages.result.another_route.support_body':
		'إذا كانت إجاباتك صحيحة وما زلت بحاجة إلى المساعدة، فقد يكون من الأفضل الحصول على مشورة مخصّصة قبل اختيار الخطوة التالية.',
	'pages.result.support_title': 'الحصول على دعم',
	'pages.result.collaborating_cta.hint':
		'استخدم دليل المنظمات للعثور على جهة متعاونة قد تتمكن من مساعدتك.',
	'pages.result.collaborating_cta.title': 'البحث عن جهة متعاونة',
	'pages.result.collaborating_cta.lead':
		'تصفح الدليل العام للجهات المتعاونة من دون إعادة الاستبيان.',
	'common.choose_month': 'اختر شهراً',
	'common.choose_one_answer': 'اختر إجابة واحدة',
	'common.choose_all_that_apply': 'اختر كل ما ينطبق',
	'eyebrows.session_setup': 'للبدء',
	'eyebrows.eligibility': 'الأهلية',
	'eyebrows.documents': 'المستندات',
	'eyebrows.support': 'احتياجات الدعم',
	'steps.language.title': 'اختر لغة',
	'steps.language.hint': 'يمكنك تغيير اللغة في أي وقت من دون فقدان إجاباتك.',
	'steps.language.check_answers_label': 'اللغة',
	'steps.language.error': 'اختر لغة.',
	'steps.language.options.es': 'Español',
	'steps.language.options.en': 'English',
	'steps.language.options.ar': 'العربية',
	'steps.language.options.fr': 'Français',
	'steps.completion_mode.title': 'لمن تملأ هذا الاستبيان؟',
	'steps.completion_mode.hint': 'اختر الخيار الذي يطابق هذه الجلسة بأفضل شكل.',
	'steps.completion_mode.check_answers_label': 'الشخص الذي تملأ له هذا الاستبيان',
	'steps.completion_mode.error': 'اختر لمن تملأ هذا الاستبيان.',
	'steps.completion_mode.options.self': 'لنفسي',
	'steps.completion_mode.options.someone_else': 'لشخص آخر، بإذنه',
	'steps.completion_mode.options.support_worker': 'أنا عامل دعم أو متطوع',
	'steps.presence_before_cutoff.title': 'هل كنت تعيش بالفعل في إسبانيا قبل 1 يناير 2026؟',
	'steps.presence_before_cutoff.hint':
		'أجب بناءً على ما إذا كنت تعيش بالفعل في إسبانيا قبل تاريخ الحد',
	'steps.presence_before_cutoff.check_answers_label': 'العيش في إسبانيا قبل 1 يناير 2026',
	'steps.presence_before_cutoff.error': 'اختر ما إذا كنت تعيش بالفعل في إسبانيا قبل 1 يناير 2026.',
	'steps.common.options.yes': 'نعم',
	'steps.common.options.no': 'لا',
	'steps.common.options.not_sure': 'لست متأكداً',
	'steps.asylum_history.title': 'هل تقدّمت بطلب لجوء أو حماية دولية في إسبانيا؟',
	'steps.asylum_history.check_answers_label': 'اللجوء أو الحماية الدولية في إسبانيا',
	'steps.asylum_history.error': 'اختر ما إذا كنت قد تقدّمت بطلب لجوء أو حماية دولية في إسبانيا.',
	'steps.asylum_before_cutoff.title': 'هل كان ذلك الطلب قبل 1 يناير 2026؟',
	'steps.asylum_before_cutoff.check_answers_label': 'اللجوء أو الحماية الدولية قبل 1 يناير 2026',
	'steps.asylum_before_cutoff.error': 'اختر ما إذا كان ذلك الطلب قبل 1 يناير 2026.',
	'steps.five_month_stay.title':
		'في الأشهر الخمسة السابقة لتاريخ تقديم الطلب الذي تخطط له، هل بقيت في إسبانيا طوال الوقت؟',
	'steps.five_month_stay.body': 'أجب عن الأشهر الخمسة السابقة لتاريخ تقديم الطلب الذي تتوقعه.',
	'steps.five_month_stay.check_answers_label': 'البقاء في إسبانيا طوال فترة الـ5 أشهر',
	'steps.five_month_stay.error': 'اختر الإجابة الأنسب لوضعك.',
	'steps.five_month_stay.options.left_spain': 'لا، غادرت إسبانيا في وقت ما',
	'steps.asylum_documents.title': 'هل لديك أي مستندات بشأن قضية اللجوء أو الحماية الخاصة بك؟',
	'steps.asylum_documents.hint': 'مثل إيصال تقديم أو مستند من الملف أو رسالة أو إشعار.',
	'steps.asylum_documents.check_answers_label': 'مستندات بشأن قضية اللجوء أو الحماية الخاصة بك',
	'steps.asylum_documents.error':
		'اختر ما إذا كانت لديك مستندات بشأن قضية اللجوء أو الحماية الخاصة بك.',
	'steps.work_situation.title': 'هل يصف أي مما يلي وضعك في العمل؟',
	'steps.work_situation.check_answers_label': 'الوضع في العمل',
	'steps.work_situation.error': 'اختر خياراً واحداً على الأقل.',
	'steps.work_situation.options.worked_in_spain': 'لقد عملت في إسبانيا',
	'steps.work_situation.options.job_offer': 'لدي عرض عمل',
	'steps.work_situation.options.want_to_work_for_myself': 'أريد العمل لحسابي الخاص',
	'steps.work_situation.options.none': 'لا شيء من ذلك',
	'steps.family_situation.title': 'هل يصف أي مما يلي وضعك العائلي في إسبانيا؟',
	'steps.family_situation.check_answers_label': 'الوضع العائلي في إسبانيا',
	'steps.family_situation.error': 'اختر خياراً واحداً على الأقل.',
	'steps.family_situation.options.child_under_18': 'أعيش مع طفلي دون سن 18',
	'steps.family_situation.options.adult_child_support_needs':
		'أعيش مع طفلي البالغ الذي يحتاج إلى دعم كبير بسبب إعاقة أو احتياجات صحية',
	'steps.family_situation.options.mother_or_father': 'أعيش مع أمي أو أبي',
	'steps.family_situation.options.none': 'لا شيء من ذلك',
	'steps.identity_documents.title': 'ما وثائق الهوية التي بحوزتك؟',
	'steps.identity_documents.check_answers_label': 'وثائق الهوية',
	'steps.identity_documents.error': 'اختر خياراً واحداً على الأقل.',
	'steps.identity_documents.options.current_passport': 'جواز سفر ساري',
	'steps.identity_documents.options.expired_passport': 'جواز سفر منتهي الصلاحية',
	'steps.identity_documents.options.national_identity_card': 'بطاقة هوية وطنية',
	'steps.identity_documents.options.asylum_document': 'وثيقة لجوء',
	'steps.identity_documents.options.travel_document': 'وثيقة سفر',
	'steps.identity_documents.options.no_identity_documents_now': 'ليست لدي الآن أي وثائق هوية معي',
	'steps.identity_documents.options.prefer_not_to_say': 'أفضل عدم الإجابة',
	'steps.evidence_before_cutoff.title':
		'هل لديك أي مستندات يمكن أن تساعد في إثبات أنك كنت تعيش بالفعل في إسبانيا قبل يناير 2026؟',
	'steps.evidence_before_cutoff.check_answers_label': 'مستندات قد تُظهر الإقامة قبل يناير 2026',
	'steps.evidence_before_cutoff.error': 'اختر خياراً واحداً على الأقل.',
	'steps.evidence_before_cutoff.options.padron_or_registration': 'تسجيل أو padrón',
	'steps.evidence_before_cutoff.options.housing_papers': 'مستندات سكن',
	'steps.evidence_before_cutoff.options.health_or_pharmacy': 'مستندات صحية أو صيدلية',
	'steps.evidence_before_cutoff.options.school_or_childcare': 'مستندات مدرسة أو رعاية أطفال',
	'steps.evidence_before_cutoff.options.work_papers': 'مستندات عمل',
	'steps.evidence_before_cutoff.options.organisation_or_church_letter':
		'رسائل من منظمة أو كنيسة أو عامل اجتماعي',
	'steps.evidence_before_cutoff.options.travel_or_transport': 'مستندات سفر أو نقل',
	'steps.evidence_before_cutoff.options.something_else_dated_named': 'مستند آخر يحمل تاريخاً واسمي',
	'steps.evidence_before_cutoff.options.none_yet': 'لا أملك أياً من هذه بعد',
	'steps.evidence_recent_months.title':
		'هل لديك أي مستندات من الأشهر الخمسة الماضية يمكن أن تساعد في إظهار أنك كنت تعيش هنا مؤخراً؟',
	'steps.evidence_recent_months.check_answers_label': 'مستندات من آخر 5 أشهر',
	'steps.evidence_recent_months.error': 'اختر خياراً واحداً على الأقل.',
	'steps.evidence_recent_months.options.housing_papers': 'مستندات سكن',
	'steps.evidence_recent_months.options.health_or_pharmacy': 'مستندات صحية أو صيدلية',
	'steps.evidence_recent_months.options.school_or_childcare': 'مستندات مدرسة أو رعاية أطفال',
	'steps.evidence_recent_months.options.work_papers': 'مستندات عمل',
	'steps.evidence_recent_months.options.organisation_or_church_letter':
		'رسائل من منظمة أو كنيسة أو عامل اجتماعي',
	'steps.evidence_recent_months.options.bank_or_money_transfer': 'سجلات مصرفية أو تحويلات مالية',
	'steps.evidence_recent_months.options.travel_or_dated_receipts': 'سفر أو إيصالات مؤرخة',
	'steps.evidence_recent_months.options.something_else_dated_named': 'مستند آخر يحمل تاريخاً واسمي',
	'steps.evidence_recent_months.options.none_yet': 'لا أملك أياً من هذه بعد',
	'steps.specialist_flags.title': 'هل هناك أي شيء قد يعني أنك تحتاج إلى مشورة متخصصة قبل التقديم؟',
	'steps.specialist_flags.check_answers_label': 'أمور قد تتطلب مشورة متخصصة',
	'steps.specialist_flags.error': 'اختر خياراً واحداً على الأقل.',
	'steps.specialist_flags.options.criminal_record_worry':
		'أشعر بالقلق من وجود سجل جنائي أو قضية جنائية',
	'steps.specialist_flags.options.identity_missing_or_mismatch':
		'وثائق هويتي مفقودة أو أن بياناتي لا تتطابق بين المستندات',
	'steps.specialist_flags.options.previous_refusal_needs_help':
		'تلقيت رفضاً في إجراء آخر وأحتاج إلى مساعدة لفهمه',
	'steps.specialist_flags.options.asylum_case_not_clear':
		'لست متأكداً مما حدث في قضية اللجوء الخاصة بي',
	'steps.specialist_flags.options.unsafe_sharing_digitally':
		'لا أشعر بالأمان عند مشاركة بعض المعلومات رقمياً',
	'steps.specialist_flags.options.urgent_human_support': 'أحتاج إلى دعم بشري عاجل',
	'steps.specialist_flags.options.want_specialist': 'أفضل التحدث مع مختص حول هذا الأمر',
	'steps.specialist_flags.options.none': 'لا شيء من ذلك',
	'steps.support_needs.check_answers_label': 'الدعم المطلوب',
	'steps.province.title': 'في أي مقاطعة أنت؟',
	'steps.province.hint': 'يساعدنا هذا في عرض خيارات الدعم القريبة منك.',
	'steps.province.check_answers_label': 'المقاطعة',
	'steps.province.error': 'اختر مقاطعة.',
	'steps.support_needs.title': 'ما نوع المساعدة الأكثر فائدة لك؟',
	'steps.support_needs.error': 'اختر خياراً واحداً على الأقل.',
	'steps.support_needs.options.another_language': 'مساعدة بلغة أخرى',
	'steps.support_needs.options.in_person_help': 'مساعدة حضورية',
	'steps.support_needs.options.phone_support': 'دعم عبر الهاتف',
	'steps.support_needs.options.help_using_phone_or_computer':
		'مساعدة في استخدام الهاتف أو الكمبيوتر',
	'steps.support_needs.options.help_scanning_or_printing':
		'مساعدة في مسح المستندات ضوئياً أو طباعتها',
	'steps.support_needs.options.help_gathering_papers': 'مساعدة لفهم المستندات التي ينبغي جمعها',
	'steps.support_needs.options.child_or_dependant_support':
		'مساعدة أيضاً للأطفال أو الأشخاص المعالين',
	'steps.support_needs.options.specialist_advice': 'مشورة متخصصة',
	'result.reason.after_cutoff': 'ذكرت أنك لم تكن تعيش بعد في إسبانيا قبل 1 يناير 2026.',
	'result.reason.specialist_review':
		'تشير واحدة أو أكثر من إجاباتك إلى أن الحصول على دعم قبل التقديم سيكون أكثر أماناً.',
	'result.reason.specialist_review_criminal_record':
		'ذكرت أنك قد تقلق بشأن السجل الجنائي. من الأسلم مراجعة ذلك مع الدعم قبل التقديم.',
	'result.reason.specialist_review_identity':
		'ذكرت أن بعض تفاصيل الهوية قد تكون مفقودة أو غير متطابقة. من الأسلم مراجعة ذلك مع الدعم قبل التقديم.',
	'result.reason.not_enough_information':
		'لا تزال بعض التفاصيل المهمة عن وضعك أو عن التسلسل الزمني غير واضحة.',
	'result.reason.more_evidence':
		'قد تتوافق إجاباتك مع هذا المسار، لكنك قد تحتاج إلى مزيد من المستندات لدعم طلبك.',
	'result.reason.likely_in_scope':
		'تشير إجاباتك إلى أن التواريخ والمستندات التي لديك قد تتوافق مع هذا المسار.',
	'result.explanation.after_cutoff':
		'استناداً إلى إجاباتك، فغالباً لا يكون هذا المسار الأنسب لأن تاريخ الحد قد لا يكون مستوفى.',
	'result.explanation.specialist_review':
		'تشير إجاباتك إلى أن مختصاً ينبغي أن يراجع وضعك قبل الخطوة التالية.',
	'result.explanation.not_enough_information': 'لا توجد معلومات كافية بعد لاقتراح أفضل خطوة تالية.',
	'result.explanation.more_evidence':
		'استناداً إلى إجاباتك، قد يكون هذا المسار مناسباً لوضعك، لكنك قد تحتاج إلى مزيد من المستندات قبل التقديم.',
	'result.explanation.likely_in_scope':
		'تشير إجاباتك إلى أنك قد تتمكن من استخدام عملية التسوية هذه.',
	'result.flag.uncertain_timeline': 'المدة الزمنية غير مؤكدة',
	'result.flag.five_month_requirement_risk': 'احتمال وجود مشكلة في الاستمرارية',
	'result.flag.hard_gate_after_cutoff': 'بدء الإقامة كان بعد التاريخ الفاصل',
	'result.flag.criminal_record_concern': 'احتمال وجود قلق متعلق بسجل جنائي',
	'result.flag.identity_issue': 'مشكلة في الهوية',
	'result.flag.asylum_complexity': 'احتمال وجود تعقيد متعلق باللجوء',
	'result.flag.missing_identity_documents': 'وثائق الهوية مفقودة',
	'result.flag.continuity_concern': 'قلق بشأن الاستمرارية',
	'result.flag.family_support_needs': 'احتياجات دعم للأسرة أو المعالين',
	'result.checklist.item.identity_document_available': 'وثيقة هوية يمكنك إبرازها.',
	'result.checklist.item.asylum_case_documents_available':
		'مستندات تتعلق بقضية اللجوء أو الحماية الخاصة بك.',
	'result.checklist.item.before_cutoff_evidence_available':
		'أوراق قد تساعد في إظهار أنك كنت في إسبانيا قبل يناير 2026.',
	'result.checklist.item.recent_evidence_available': 'أوراق حديثة من آخر 5 أشهر.',
	'result.checklist.item.continuity_answer_positive':
		'إقامة حديثة في إسبانيا قد تتوافق مع هذا المسار.',
	'result.checklist.item.identity_document_needed': 'وثيقة هوية يمكنك استخدامها في الطلب.',
	'result.checklist.item.before_cutoff_evidence_needed':
		'أوراق مؤرخة تُظهر أنك كنت في إسبانيا قبل يناير 2026.',
	'result.checklist.item.recent_evidence_needed': 'أوراق حديثة من آخر 5 أشهر.',
	'result.checklist.item.asylum_case_documents_needed':
		'أي أوراق ما زالت لديك عن قضية لجوء أو حماية، إذا كان ذلك ينطبق على وضعك.',
	'result.checklist.item.official_document_requirements':
		'أحدث المتطلبات الرسمية للمستندات، بما في ذلك مستندات السجل الجنائي إذا كانت تنطبق على حالتك.',
	'result.checklist.item.practical_support_helpful':
		'مساعدة في اللغة أو الوصول الرقمي أو المسح الضوئي أو الطباعة أو فهم المستندات الأكثر أهمية.',
	'result.checklist.item.complex_case_review':
		'أي قلق يتعلق بالسجل الجنائي أو الهوية أو تاريخ اللجوء أو مشاركة المعلومات بأمان.',
	'result.checklist.item.another_route_advice': 'ما إذا كان مسار هجرة آخر قد يكون أنسب.',
	'result.checklist.item.confirm_timeline':
		'ما إذا كنت بالفعل في إسبانيا قبل 1 يناير 2026، وما إذا بقيت في إسبانيا طوال فترة الـ5 أشهر قبل تقديم الطلب.',
	'result.checklist.item.continuity_concern': 'أي فجوات أو غياب خلال الأشهر الخمسة الماضية.',
	'result.checklist.item.identity_issue_to_explain': 'أي وثائق هوية مفقودة أو تفاصيل لا تتطابق.',
	'result.checklist.item.asylum_history_to_explain':
		'ما الذي حدث في أي إجراء لجوء أو حماية في إسبانيا.',
	'result.title.likely_in_scope': 'من المرجّح أن هذه الحالة تنطبق عليك',
	'result.title.possible_but_needs_more_evidence':
		'قد يكون هذا المسار مناسباً، لكنك قد تحتاج إلى مزيد من المستندات أولاً',
	'result.title.needs_specialist_review': 'يحتاج إلى مراجعة متخصصة',
	'result.title.another_route_may_fit_better': 'غالباً ليس هذا هو المسار المناسب لك',
	'result.title.not_enough_information_yet':
		'نحتاج إلى مزيد قليل من المعلومات قبل اقتراح الخطوة التالية'
} satisfies Partial<Record<MessageKey, string>>
