export const en = {
	'common.not_answered': 'Not answered',
	'common.choose_an_option': 'Choose an option',
	'common.continue': 'Continue',
	'common.back': 'Back',
	'common.problem': 'There is a problem',
	'chrome.skip_to_main': 'Skip to main content',
	'chrome.app_title': 'Primer Paso',
	'chrome.meta_description':
		"Primer Paso is an intake screener for Spain's 2026 extraordinary regularisation process. Hosted at primerpaso.org.",
	'chrome.brand': 'Primer Paso',
	'chrome.tagline': "Independent guidance for Spain's 2026 regularisation process",
	'chrome.primary_navigation': 'Primary navigation',
	'chrome.nav.home': 'Home',
	'chrome.nav.start': 'Check next step',
	'chrome.nav.organisations': 'Find organisations',
	'chrome.language_switcher_label': 'Language',
	'pages.home.eyebrow': 'Getting started',
	'pages.home.title': 'Choose how you want to start',
	'pages.home.lead':
		'You can use the screener to check your next step or go straight to the directory of collaborating organisations.',
	'pages.home.choose': 'Choose an option',
	'pages.home.quiz_title': 'Check my next step',
	'pages.home.quiz_body':
		'Answer a few questions to get cautious guidance on which route may fit your situation best.',
	'pages.home.quiz_action': 'Start the screener',
	'pages.home.directory_title': 'Find a collaborating organisation',
	'pages.home.directory_body':
		'Browse the directory without completing the form. Search by name, province, or contact details.',
	'pages.home.directory_action': 'Open directory',
	'pages.home.note_title': 'Before you begin',
	'pages.home.note_body':
		'This service offers practical guidance. It does not replace legal advice or an official decision.',
	'pages.start.eyebrow': 'Milestone 1',
	'pages.organisations.meta_title': 'Find organisations',
	'pages.organisations.meta_description':
		'Browse collaborating organisations by name, province, and contact details.',
	'pages.organisations.eyebrow': 'Collaborating organisations',
	'pages.organisations.title': 'Find a collaborating organisation',
	'pages.organisations.lead':
		'Browse the public directory without completing the screener. Search by name, location, or contact details.',
	'pages.organisations.search_label': 'Search',
	'pages.organisations.search_placeholder': 'Search by name, place, phone, email, or website',
	'pages.organisations.apply_filters': 'Apply filters',
	'pages.organisations.clear': 'Clear',
	'pages.organisations.summary.one': '{count} organisation found',
	'pages.organisations.summary.many': '{count} organisations found',
	'pages.organisations.summary.with_website': '{count} with website',
	'pages.organisations.summary.with_phone': '{count} with phone',
	'pages.organisations.summary.with_email': '{count} with email',
	'pages.organisations.badge.website': 'website available',
	'pages.organisations.badge.phone': 'phone available',
	'pages.organisations.badge.email': 'email available',
	'pages.organisations.empty_title': 'No organisations match these filters',
	'pages.organisations.empty_body': 'Try a broader search or browse the full directory.',
	'pages.organisations.guidance_title': 'Need personalised guidance first?',
	'pages.organisations.guidance_body':
		'If you are not sure where to start, use the screener and then come back to the directory.',
	'pages.organisations.action.visit_website': 'Visit website',
	'pages.organisations.action.email': 'Email',
	'pages.organisations.action.call': 'Call',
	'pages.organisations.action.browse_all': 'Browse all organisations',
	'pages.organisations.action.start_screener': 'Start the screener',
	'pages.start.title': 'Check what support you may need for the regularisation process',
	'pages.start.lead': 'Use this checker to understand your likely next step.',
	'pages.start.not_official': 'This is not the official government application.',
	'pages.start.window_open': 'The official application window is open until 30 June 2026.',
	'pages.start.resume': 'You can stop and come back later.',
	'pages.start.what_to_expect_title': 'What to expect',
	'pages.start.expectation.duration': 'about 5 to 8 minutes',
	'pages.start.expectation.one_question': 'one question at a time',
	'pages.start.expectation.review': 'a review step before the result',
	'pages.start.expectation.timeline':
		'whether you were in Spain before 1 January 2026 and stayed in Spain for the whole 5-month period before applying',
	'pages.start.start_now': 'Start the questionnaire',
	'pages.check_answers.eyebrow': 'Review',
	'pages.check_answers.title': 'Check your answers',
	'pages.check_answers.hint': 'Check these answers before you continue. You can change any answer.',
	'pages.check_answers.change': 'Change',
	'pages.check_answers.see_result': 'See result',
	'pages.check_answers.back': 'Back',
	'pages.handover.eyebrow': 'Handover',
	'pages.handover.summary_title': 'Summary',
	'pages.handover.title': 'Handover summary',
	'pages.handover.body':
		'Use this PDF to keep a copy of your answers or to share them with a trusted support worker or collaborating organisation.',
	'pages.handover.reference': 'Reference number: {sessionId}',
	'pages.handover.generated_at': 'Generated: {generatedAt}',
	'pages.handover.generated_by': 'Generated by Primer Paso (primerpaso.org)',
	'pages.handover.links_title': 'Useful links',
	'pages.handover.link.official_portal': 'Official regularisation portal',
	'pages.handover.link.collaborators_pdf': 'Official list of collaborating organisations',
	'pages.handover.next_step_title': 'Recommended next step',
	'pages.handover.checklist_title': 'What to get ready',
	'pages.handover.answers_title': 'Your answers',
	'pages.handover.flags_title': 'Points that may need attention',
	'pages.handover.action.print': 'Print this summary',
	'pages.handover.action.back_to_result': 'Back to result',
	'pages.result.eyebrow': 'Result',
	'pages.result.eligibility_title': 'Likely eligibility',
	'pages.result.eligibility.likely_in_scope':
		'Based on your answers, this regularisation route may fit your situation.',
	'pages.result.eligibility.possible_but_needs_more_evidence':
		'Based on your answers, this route may fit, but you may need more documents before you apply.',
	'pages.result.eligibility.needs_specialist_review':
		'Based on your answers, this route may still fit, but it would be safer to review it with support before you apply.',
	'pages.result.eligibility.not_enough_information_yet':
		'It is not yet clear whether this route fits, because some important information is still missing or uncertain.',
	'pages.result.eligibility.another_route_may_fit_better':
		'Based on your answers, another immigration route may fit better.',
	'pages.result.next_step_title': 'Your next step',
	'pages.result.next_step.official_portal':
		'Go to the official regularisation portal when you are ready to continue.',
	'pages.result.next_step.collaborating_organisation':
		'Take this summary to a collaborating organisation before you continue.',
	'pages.result.next_step.collaborating_organisation_hint':
		'Open the official list and choose a collaborating organisation that can review your case with you.',
	'pages.result.why_title': 'Why we think this',
	'pages.result.checklist_title': 'What to get ready',
	'pages.result.checklist.already_have': 'What you already have',
	'pages.result.checklist.still_need': 'What you may still need',
	'pages.result.checklist.discuss_with_support': 'What to ask about when you get support',
	'pages.result.checklist.unresolved': 'What to check or explain',
	'pages.result.route.official_portal_body':
		'Use the official government portal for the regularisation process. If you need help first, you can also take this summary to a collaborating organisation.',
	'pages.result.route.collaborating_organisation_body':
		'Start with the official list of collaborating organisations. Take this summary with you so they do not have to start again from the beginning.',
	'pages.result.handover_title': 'Save, print or share your summary',
	'pages.result.handover.body':
		'Keep a copy of your answers. You can also take this summary to a trusted support worker or collaborating organisation.',
	'pages.result.how_to_apply_title': 'Before you apply',
	'pages.result.how_to_apply.body':
		'Use the official government application channel and do not leave it until the last minute.',
	'pages.result.how_to_apply.hint': 'The official application window is open until 30 June 2026.',
	'pages.result.support_title': 'Get support',
	'pages.result.support.body':
		'This checker is not legal advice. Support near you may depend on your province: {province}.',
	'pages.result.flags_title': 'Flags raised',
	'pages.result.reference_title': 'Keep this reference',
	'pages.result.reference_body': 'Reference number: {sessionId}',
	'pages.result.action.official_portal': 'Use official regularisation portal',
	'pages.result.action.open_official_portal': 'Open official regularisation portal',
	'pages.result.action.open_collaborators_pdf': 'Open official list of collaborating organisations',
	'pages.result.action.collaborators_pdf': 'See official list of collaborating organisations',
	'pages.result.action.print_handover': 'Download handover PDF',
	'pages.result.action.download_handover_json': 'Download handover JSON',
	'pages.result.action.back_to_answers': 'Back to answers',
	'pages.result.action.start_again': 'Start again',
	'pages.confirmation.eyebrow': 'Confirmation',
	'pages.confirmation.title': 'Your result is ready',
	'pages.confirmation.body':
		'Keep this page. It includes your reference number and a copy of your answers.',
	'pages.confirmation.reference_number': 'Reference number',
	'pages.confirmation.updated': 'Updated',
	'pages.confirmation.hint': 'Save, print, or screenshot this page.',
	'pages.confirmation.action.view_answers': 'View your answers',
	'pages.confirmation.action.back_to_result': 'Back to result',
	'pages.confirmation.action.start_again': 'Start again',
	'common.choose_month': 'Choose month',
	'common.choose_one_answer': 'Choose one answer',
	'common.choose_all_that_apply': 'Choose all that apply',
	'eyebrows.session_setup': 'Getting started',
	'eyebrows.eligibility': 'Eligibility',
	'eyebrows.route_split': 'Eligibility',
	'eyebrows.route_asylum': 'Documents',
	'eyebrows.route_non_asylum': 'Eligibility',
	'eyebrows.identity': 'Documents',
	'eyebrows.documents': 'Documents',
	'eyebrows.evidence_cutoff': 'Documents',
	'eyebrows.evidence_recent': 'Documents',
	'eyebrows.specialist': 'Support needs',
	'eyebrows.routing': 'Support needs',
	'eyebrows.referral': 'Local support',
	'eyebrows.support': 'Support needs',
	'eyebrows.contact': 'How we can contact you',
	'months.january': 'January',
	'months.february': 'February',
	'months.march': 'March',
	'months.april': 'April',
	'months.may': 'May',
	'months.june': 'June',
	'months.july': 'July',
	'months.august': 'August',
	'months.september': 'September',
	'months.october': 'October',
	'months.november': 'November',
	'months.december': 'December',
	'steps.language.title': 'Choose a language',
	'steps.language.hint': 'You can change language at any time without losing your answers.',
	'steps.language.check_answers_label': 'Language',
	'steps.language.error': 'Choose a language.',
	'steps.language.options.es': 'Español',
	'steps.language.options.en': 'English',
	'steps.language.options.ar': 'العربية',
	'steps.language.options.fr': 'Français',
	'steps.completion_mode.title': 'Who are you filling this in for?',
	'steps.completion_mode.hint': 'Choose the option that best matches this session.',
	'steps.completion_mode.check_answers_label': 'Who you are filling this in for',
	'steps.completion_mode.error': 'Choose who you are filling this in for.',
	'steps.completion_mode.options.self': 'Myself',
	'steps.completion_mode.options.someone_else': 'Someone else, with their permission',
	'steps.completion_mode.options.support_worker': "I'm a support worker or volunteer",
	'steps.presence_before_cutoff.title': 'Were you already living in Spain before 1 January 2026?',
	'steps.presence_before_cutoff.hint':
		'Answer based on whether you were already living in Spain before the cut-off date',
	'steps.presence_before_cutoff.check_answers_label': 'Living in Spain before 1 January 2026',
	'steps.presence_before_cutoff.error':
		'Choose whether you were already living in Spain before 1 January 2026.',
	'steps.common.options.yes': 'Yes',
	'steps.common.options.no': 'No',
	'steps.common.options.not_sure': "I'm not sure",
	'steps.residence_start.title': 'When did you start living in Spain?',
	'steps.residence_start.hint': 'An approximate month is enough.',
	'steps.residence_start.check_answers_label': 'When you started living in Spain',
	'steps.residence_start.error': 'Choose when you started living in Spain.',
	'steps.residence_start.month_error':
		'Choose the month, or say that you are not sure about the month.',
	'steps.residence_start.options.2024_or_earlier': 'In 2024 or earlier',
	'steps.residence_start.options.2025': 'In 2025',
	'steps.residence_start.options.2026': 'In 2026',
	'steps.residence_start.options.not_sure': "I'm not sure",
	'steps.residence_start.month_prompt': 'Which month was that, roughly?',
	'steps.residence_start.month_unknown': "I'm not sure about the month",
	'steps.asylum_history.title': 'Did you apply for asylum or international protection in Spain?',
	'steps.asylum_history.check_answers_label': 'Asylum or international protection in Spain',
	'steps.asylum_history.error':
		'Choose whether you applied for asylum or international protection in Spain.',
	'steps.asylum_before_cutoff.title': 'Was that application before 1 January 2026?',
	'steps.asylum_before_cutoff.check_answers_label':
		'Asylum or international protection before 1 January 2026',
	'steps.asylum_before_cutoff.error': 'Choose whether that application was before 1 January 2026.',
	'steps.five_month_stay.title':
		'In the 5 months before you plan to apply, did you stay in Spain the whole time?',
	'steps.five_month_stay.body': 'Answer about the 5 months before you expect to apply.',
	'steps.five_month_stay.check_answers_label': 'Stayed in Spain for the whole 5-month period',
	'steps.five_month_stay.error': 'Choose the answer that fits your situation best.',
	'steps.five_month_stay.options.left_spain': 'No, I left Spain at some point',
	'steps.asylum_documents.title': 'Do you have any documents about your asylum or protection case?',
	'steps.asylum_documents.hint':
		'For example, a filing receipt, case document, letter or notification.',
	'steps.asylum_documents.check_answers_label': 'Documents about your asylum or protection case',
	'steps.asylum_documents.error':
		'Choose whether you have documents about your asylum or protection case.',
	'steps.work_situation.title': 'Does any of this describe your work situation?',
	'steps.work_situation.check_answers_label': 'Work situation',
	'steps.work_situation.error': 'Choose at least one option.',
	'steps.work_situation.options.worked_in_spain': "I've worked in Spain",
	'steps.work_situation.options.job_offer': 'I have a job offer',
	'steps.work_situation.options.want_to_work_for_myself': 'I want to work for myself',
	'steps.work_situation.options.none': 'None of these',
	'steps.family_situation.title': 'Does any of this describe your family situation in Spain?',
	'steps.family_situation.check_answers_label': 'Family situation in Spain',
	'steps.family_situation.error': 'Choose at least one option.',
	'steps.family_situation.options.child_under_18': 'I live with my child who is under 18',
	'steps.family_situation.options.adult_child_support_needs':
		'I live with my adult child who needs a lot of support because of disability or health needs',
	'steps.family_situation.options.mother_or_father': 'I live with my mother or father',
	'steps.family_situation.options.none': 'None of these',
	'steps.identity_documents.title': 'Which identity papers do you have?',
	'steps.identity_documents.check_answers_label': 'Identity papers',
	'steps.identity_documents.error': 'Choose at least one option.',
	'steps.identity_documents.options.current_passport': 'Current passport',
	'steps.identity_documents.options.expired_passport': 'Expired passport',
	'steps.identity_documents.options.national_identity_card': 'National identity card',
	'steps.identity_documents.options.asylum_document': 'Asylum document',
	'steps.identity_documents.options.travel_document': 'Travel document',
	'steps.identity_documents.options.no_identity_documents_now':
		'I do not have any identity documents with me now',
	'steps.identity_documents.options.prefer_not_to_say': 'Prefer not to say',
	'steps.evidence_before_cutoff.title':
		'Do you have any documents that could help show you were already living in Spain before January 2026?',
	'steps.evidence_before_cutoff.check_answers_label':
		'Papers that may show residence before January 2026',
	'steps.evidence_before_cutoff.error': 'Choose at least one option.',
	'steps.evidence_before_cutoff.options.padron_or_registration': 'Registration or padrón',
	'steps.evidence_before_cutoff.options.housing_papers': 'Housing papers',
	'steps.evidence_before_cutoff.options.health_or_pharmacy': 'Health or pharmacy papers',
	'steps.evidence_before_cutoff.options.school_or_childcare': 'School or childcare papers',
	'steps.evidence_before_cutoff.options.work_papers': 'Work papers',
	'steps.evidence_before_cutoff.options.organisation_or_church_letter':
		'Letters from an organisation, church, or social worker',
	'steps.evidence_before_cutoff.options.travel_or_transport': 'Travel or transport papers',
	'steps.evidence_before_cutoff.options.something_else_dated_named':
		'Something else with a date and my name on it',
	'steps.evidence_before_cutoff.options.none_yet': 'I do not have any of these yet',
	'steps.evidence_recent_months.title':
		"Do you have any documents from the last 5 months that could help show you've been living here recently?",
	'steps.evidence_recent_months.check_answers_label': 'Papers from the last 5 months',
	'steps.evidence_recent_months.error': 'Choose at least one option.',
	'steps.evidence_recent_months.options.housing_papers': 'Housing papers',
	'steps.evidence_recent_months.options.health_or_pharmacy': 'Health or pharmacy papers',
	'steps.evidence_recent_months.options.school_or_childcare': 'School or childcare papers',
	'steps.evidence_recent_months.options.work_papers': 'Work papers',
	'steps.evidence_recent_months.options.organisation_or_church_letter':
		'Letters from an organisation, church, or social worker',
	'steps.evidence_recent_months.options.bank_or_money_transfer': 'Bank or money transfer records',
	'steps.evidence_recent_months.options.travel_or_dated_receipts': 'Travel or dated receipts',
	'steps.evidence_recent_months.options.something_else_dated_named':
		'Something else with a date and my name on it',
	'steps.evidence_recent_months.options.none_yet': 'I do not have any of these yet',
	'steps.specialist_flags.title':
		'Is there anything that might mean you need specialist advice before applying?',
	'steps.specialist_flags.check_answers_label': 'Anything that may need specialist advice',
	'steps.specialist_flags.error': 'Choose at least one option.',
	'steps.specialist_flags.options.criminal_record_worry':
		"I'm worried about a criminal record or criminal case",
	'steps.specialist_flags.options.identity_missing_or_mismatch':
		'My identity papers are missing or my details do not match across documents',
	'steps.specialist_flags.options.previous_refusal_needs_help':
		'I had a refusal in another procedure and need help understanding it',
	'steps.specialist_flags.options.asylum_case_not_clear':
		"I'm not sure what happened with my asylum case",
	'steps.specialist_flags.options.unsafe_sharing_digitally':
		'I do not feel safe sharing some information digitally',
	'steps.specialist_flags.options.urgent_human_support': 'I need urgent human support',
	'steps.specialist_flags.options.want_specialist':
		"I'd rather talk this through with a specialist",
	'steps.specialist_flags.options.none': 'None of these',
	'steps.support_needs.check_answers_label': 'Support needed',
	'steps.province.title': 'Which province are you in?',
	'steps.province.hint': 'This helps us show support options near you.',
	'steps.province.check_answers_label': 'Province',
	'steps.province.error': 'Choose a province.',
	'steps.province.options.madrid': 'Madrid',
	'steps.province.options.barcelona': 'Barcelona',
	'steps.province.options.valencia': 'Valencia',
	'steps.province.options.sevilla': 'Sevilla',
	'steps.province.options.malaga': 'Málaga',
	'steps.province.options.alicante': 'Alicante',
	'steps.province.options.bizkaia': 'Bizkaia',
	'steps.province.options.zaragoza': 'Zaragoza',
	'steps.province.options.murcia': 'Murcia',
	'steps.province.options.other': 'Another province',
	'steps.referral.title': 'Do you want help with the next step?',
	'steps.referral.body':
		'Based on your result, you might want help gathering papers, speaking to a specialist, or making your application.',
	'steps.referral.error': 'Choose what kind of help you want next.',
	'steps.referral.options.contact_me': "Yes, I'd like someone to contact me",
	'steps.referral.options.show_options': 'Yes, show me support options near me',
	'steps.referral.options.no_thanks': "No, I'll keep this for now",
	'steps.support_needs.title': 'What kind of help would be most useful?',
	'steps.support_needs.error': 'Choose at least one option.',
	'steps.support_needs.options.another_language': 'Help in another language',
	'steps.support_needs.options.in_person_help': 'In-person help',
	'steps.support_needs.options.phone_support': 'Phone support',
	'steps.support_needs.options.help_using_phone_or_computer': 'Help using a phone or computer',
	'steps.support_needs.options.help_scanning_or_printing': 'Help scanning or printing papers',
	'steps.support_needs.options.help_gathering_papers': 'Help understanding which papers to gather',
	'steps.support_needs.options.child_or_dependant_support': 'Help with children or dependants too',
	'steps.support_needs.options.specialist_advice': 'Specialist advice',
	'steps.contact.title': 'How should we contact you?',
	'steps.contact.hint': 'Choose the safest way.',
	'steps.contact.error': 'Choose how we should contact you.',
	'steps.contact.detail_required_error': 'Enter the contact detail for the method you chose.',
	'steps.contact.detail_label': 'Contact detail',
	'steps.contact.options.sms': 'SMS',
	'steps.contact.options.whatsapp': 'WhatsApp',
	'steps.contact.options.phone': 'Phone call',
	'steps.contact.options.email': 'Email',
	'steps.contact.options.do_not_contact_yet': 'Do not contact me yet',
	'steps.contact.options.through_organisation': 'Through the organisation helping me now',
	'answers.residence_start.2024_or_earlier': '2024 or earlier',
	'answers.residence_start.2026': '2026',
	'answers.residence_start.not_sure': "I'm not sure",
	'answers.residence_start.2025': '2025',
	'answers.residence_start.2025_month_unknown': '2025 — month not sure',
	'answers.residence_start.2025_month': '{month} 2025',
	'answers.contact.with_value': '{method}: {value}',
	'result.reason.after_cutoff': 'You said you were not yet living in Spain before 1 January 2026.',
	'result.reason.specialist_review':
		'One or more of your answers suggests that it would be safer to get support before you apply.',
	'result.reason.specialist_review_criminal_record':
		'You said you may have a criminal record concern. It would be safer to review this with support before you apply.',
	'result.reason.specialist_review_identity':
		'You said some identity details may be missing or may not match. It would be safer to review this with support before you apply.',
	'result.reason.not_enough_information':
		'Some important details about your timeline or situation are still unclear.',
	'result.reason.more_evidence':
		'Your answers may fit this route, but you may need more documents to support your application.',
	'result.reason.likely_in_scope':
		'Your answers suggest that your timeline and documents may fit this route.',
	'result.explanation.after_cutoff':
		'Based on your answers, this route probably is not the best fit because the cut-off date may not be met.',
	'result.explanation.specialist_review':
		'Your answers suggest that a specialist should review your situation before the next step.',
	'result.explanation.not_enough_information':
		'There is not enough information yet to suggest the best next step.',
	'result.explanation.more_evidence':
		'Based on your answers, this route may fit your situation, but you may need more papers before you apply.',
	'result.explanation.likely_in_scope':
		'Your answers suggest you may be able to use this regularisation process.',
	'result.next_step.other_route_advice':
		'Get advice on whether another immigration route fits your situation better.',
	'result.next_step.try_again_later':
		'If your situation changes, you can check this route again later.',
	'result.next_step.keep_residence_documents':
		'Keep any documents that show your residence history in Spain.',
	'result.next_step.speak_to_specialist':
		'Speak to a specialist support organisation before you apply.',
	'result.next_step.keep_papers_together':
		'Keep your identity papers and any dated evidence together for review.',
	'result.next_step.confirm_timeline':
		'Try to confirm whether you were already in Spain before 1 January 2026 and whether you stayed in Spain for the whole 5-month period before applying.',
	'result.next_step.ask_for_help_if_unsure':
		'If you are unsure, use assisted completion or ask a support organisation to help you.',
	'result.next_step.gather_before_cutoff':
		'Try to gather dated papers that show you were living in Spain before January 2026.',
	'result.next_step.gather_recent': 'Also gather recent papers from the last 5 months if you can.',
	'result.next_step.use_official_channel':
		'Use the official application channel before 30 June 2026.',
	'result.flag.uncertain_timeline': 'Timeline is uncertain',
	'result.flag.five_month_requirement_risk': 'Possible continuity risk',
	'result.flag.hard_gate_after_cutoff': 'Residence start is after the cut-off',
	'result.flag.criminal_record_concern': 'Possible criminal record concern',
	'result.flag.identity_issue': 'Identity issue',
	'result.flag.asylum_complexity': 'Possible asylum complexity',
	'result.flag.missing_identity_documents': 'Missing identity documents',
	'result.flag.continuity_concern': 'Continuity concern',
	'result.flag.family_support_needs': 'Family or dependant support needs',
	'result.checklist.item.identity_document_available': 'An identity document you can show.',
	'result.checklist.item.asylum_case_documents_available':
		'Documents about your asylum or protection case.',
	'result.checklist.item.before_cutoff_evidence_available':
		'Papers that may show you were in Spain before January 2026.',
	'result.checklist.item.recent_evidence_available': 'Recent papers from the last 5 months.',
	'result.checklist.item.continuity_answer_positive':
		'A recent stay in Spain that may fit this route.',
	'result.checklist.item.identity_document_needed':
		'An identity document you can use for the application.',
	'result.checklist.item.before_cutoff_evidence_needed':
		'Dated papers showing you were in Spain before January 2026.',
	'result.checklist.item.recent_evidence_needed': 'Recent papers from the last 5 months.',
	'result.checklist.item.asylum_case_documents_needed':
		'Any papers you still have about an asylum or protection case, if that applies to you.',
	'result.checklist.item.official_document_requirements':
		'The latest official document requirements, including criminal record documents if they apply to you.',
	'result.checklist.item.practical_support_helpful':
		'Help with language, digital access, scanning, printing or understanding which papers matter.',
	'result.checklist.item.complex_case_review':
		'Any concern about criminal records, identity, asylum history or sharing information safely.',
	'result.checklist.item.another_route_advice': 'Whether another immigration route may fit better.',
	'result.checklist.item.confirm_timeline':
		'Whether you were already in Spain before 1 January 2026, and whether you stayed in Spain for the whole 5-month period before applying.',
	'result.checklist.item.continuity_concern': 'Any gaps or absences during the last 5 months.',
	'result.checklist.item.identity_issue_to_explain':
		'Any missing identity papers or details that do not match.',
	'result.checklist.item.asylum_history_to_explain':
		'What happened in any asylum or protection process in Spain.',
	'result.title.likely_in_scope': 'Likely in scope',
	'result.title.possible_but_needs_more_evidence':
		'This route may fit, but you may need more papers first',
	'result.title.needs_specialist_review': 'Needs specialist review',
	'result.title.another_route_may_fit_better': 'This probably is not the right route for you',
	'result.title.not_enough_information_yet':
		'We need a bit more information before suggesting a next step',
	'result.lead.likely_in_scope': 'You may be able to use this route',
	'result.lead.possible_but_needs_more_evidence':
		'This route may fit, but you may need more papers first',
	'result.lead.needs_specialist_review': 'You may need specialist help before applying',
	'result.lead.not_enough_information_yet':
		'We need a bit more information before suggesting a next step',
	'result.lead.another_route_may_fit_better': 'This probably is not the right route for you'
} as const
